### ISSUE TITLE
`react-scripts build` fails to compile generated parser

### ISSUE THREAD

**Issue by manubb** [GerHobbelt/jison#15]
I have the following errors:
  Line 1008:  'assert' is not defined     no-undef
  Line 1506:  'yyrulelen' is not defined  no-undef
  Line 1525:  'yyrulelen' is not defined  no-undef

Can you publish a fixed version, please?
(Thank you very much as i really need a fix for this!)

**Comment by GerHobbelt** [comment]
Work on this is under way. A new release should be due in a few days...

**Comment by manubb** [comment]
Great! Thank you for you support.

**Comment by GerHobbelt** [comment]
Check out the new release 0.6.1-200: that one should now produce correct parsers again. (though 'assert' is still in there, but the parser kernel defines it when it's not present in the run-time environment; 

> see also commit SHA-1: 2b8bad362f31f749d4d7e827ac8a5ac648253c7c :: several edits due to us finding out that ES6+ES5 via rollup+babel will nuke several very important code chunks, while are serialized into the generated parser: these must be (template) strings now as the `String(f)` of function `f()` trick won't fly with rollup/babel tree shaking heuristics. Also note that the parser kernel now uses `ASSERT()` instead of `assert()` as the latter **cannot** be replaced, as reported by rollup/NodeJS.

**Comment by manubb** [comment]
I gave a try to version 0.6.1-203. and there is still a problem with `assert` being undefined.

**Comment by GerHobbelt** [comment]
Can you provide an example how to reproduce that error? That would help a lot in diagnosing the problem.

**Comment by manubb** [comment]
Sorry for the delay. The generated parser contains:
```js
...
    var ASSERT;
    if (typeof assert !== 'function') {
        ASSERT = function JisonAssert(cond, msg) {
            if (!cond) {
                throw new Error('assertion failed: ' + (msg || '***'));
            }
        };
    } else {
        ASSERT = assert; // 'assert' is not defined error on this ligne
    }
...
```

**Comment by GerHobbelt** [comment]
I was wondering how that code could trigger an error but now that I look at your report very closely I notice the error lines you mention: those look like they're coming from jscs or a similar eslint / lint utility and are not run-time errors but rather a linter tool telling you it's found stuff (globals, in this case) it doesn't know about: `no-undef`.

You can quiet your eslint/jscs/... tool by configuring it to become aware of `assert` as a global, see e.g. https://eslint.org/docs/rules/no-undef


## Rationale behind the run-time kernel code you quote

The code as such is correct and intentional: it detects the *possible* presence of a global `assert` function (which is the case in many NodeJS and unit-test-executing browser environments) and when it's not, to 'shim' the `ASSERT()` function.

I define a `ASSERT` which either references the existing `assert` global or shims it to appease code-transformation tools such as `rollup` and `babel` which throw a hard error during transpiling the generated code from ES6..ES2017 to ES5 when I previously shimmed the `assert` global directly.

The code is correct: as intended and now tested okay in various NodeJS and browser run-time environments.

If this code triggers a fault/error in any run-time environment that I may have missed, please re-open issue, otherwise it's just a matter of configuring your linter to pass the generated kernel code.

## Principally Supported Run-Time Environments

- NodeJS 4.x to latest (8.x.x)
- 'modern major-brand browsers'
- **definitely not supported**: IE8 and older.
- IE9 is a possibly-maybe when the fix for the trouble it causes is deemed 'reasonable'.
- **definitely not supported**: antique NodeJS versions (0.12 and older)

**Comment by manubb** [comment]
Thank for your reply. This is indeed a eslint config issue. Sorry if this was unclear in my first message.
